resolver: lts-11.5

packages:
- ./2012
- location:
    git: https://github.com/mebubo/haskelldb.git
    commit: 22c59df0dafcf7ace9d9f8cd1d66c994b942f7e3
  extra-dep: true
- ./2013

extra-deps:
- digestive-functors-0.8.3.0
- digestive-functors-blaze-0.6.2.0
- digestive-functors-snap-0.7.0.0
- sbv-5.15
