resolver: lts-9.11

packages:
- ./2012

extra-deps:
- digestive-functors-0.8.2.0
- digestive-functors-blaze-0.6.1.0
- digestive-functors-snap-0.7.0.0
- blaze-html-0.8.1.3
- blaze-markup-0.7.1.1
- snap-1.0.0.2
- heist-1.0.1.0
- map-syntax-0.2.0.2
- xmlhtml-0.2.4
