name: doh2012

dependencies:
    - base
    - text

executables:
    exe-02:
        source-dirs: src/02-digestive-functors
        main: Main.hs
        dependencies:
            - digestive-functors
            - digestive-functors-blaze
            - blaze-html
            - snap-core
            - snap-server
            - snap
            - snap-blaze
            - digestive-functors-snap
    exe-03:
        source-dirs: src/03-sqlite-simple
        main: Main.hs
        dependencies:
            - sqlite-simple
    exe-04:
        source-dirs: src/04-errors
        main: Main.hs
        dependencies:
            - errors
            - transformers
    exe-06:
        source-dirs: src/06-containers
        main: Main.hs
        dependencies:
            - containers
    exe-07:
        source-dirs: src/07-aeson
        main: Main.hs
        dependencies:
            - aeson
            - containers
    exe-08:
        source-dirs: src/08-QuickCheck
        main: Main.hs
        dependencies:
            - QuickCheck
    exe-09:
        source-dirs: src/09-lens
        main: Main.hs
        dependencies:
            - lens
    exe-10:
        source-dirs: src/10-parsec
        main: Main.hs
        dependencies:
            - parsec
    exe-11:
        source-dirs: src/11-ekg
        main: Main.hs
        dependencies:
            - ekg
            - ekg-core
    exe-14:
        source-dirs: src/14-dlist
        main: Main.hs
        dependencies:
            - dlist
    exe-15:
        source-dirs: src/15-haskelldb
        main: Main.hs
        dependencies:
            - haskelldb
    exe-16:
        source-dirs: src/16-pipes
        main: Main.hs
        dependencies:
            - pipes
    exe-17:
        source-dirs: src/17-optparse-applicative
        main: Main.hs
        dependencies:
            - optparse-applicative
    exe-18:
        source-dirs: src/18-criterion
        main: Main.hs
        dependencies:
            - criterion
    exe-19:
        source-dirs: src/19-snap
        main: Main.hs
        dependencies:
            - snap-core
            - snap-server
            - snap
            - snaplet-sqlite-simple
            - lens
    exe-20:
        source-dirs: src/20-transformers
        main: Main.hs
        dependencies:
            - transformers
    exe-21:
        source-dirs: src/21-configurator
        main: Main.hs
        dependencies:
            - configurator
