name: doh2012

dependencies:
    - base
    - text

executables:
    exe-02:
        source-dirs: src/02-digestive-functors
        main: Main.hs
        dependencies:
            - digestive-functors
            - digestive-functors-blaze
            - blaze-html
            - snap-core
            - snap-server
            - snap
            - snap-blaze
            - digestive-functors-snap
    exe-03:
        source-dirs: src/03-sqlite-simple
        main: Main.hs
        dependencies:
            - sqlite-simple
