name: doh2013

dependencies:
  - base

executables:
  linear:
    source-dirs: src/02-linear
    main: Main.hs
    dependencies:
      - linear
      - containers
      - lens
  tasty:
    source-dirs: src/03-tasty
    main: Main.hs
    dependencies:
      - tasty
      - tasty-smallcheck
      - tasty-hunit
  scotty:
    source-dirs: src/05-scotty
    main: Main.hs
    dependencies:
      - scotty
      - aeson
      - http-types
  # persistent-esqueleto:
  #   source-dirs: src/06-presistent-esqueleto
  #   main: Main.hs
  #   dependencies:
  #     - persistent
  #     - persistent-template
  #     - persistent-sqlite
  #     - text
  #     - time
  #     - esqueleto
  threepenny-gui:
    source-dirs: src/07-threepenny-gui
    main: Main.hs
    dependencies:
      - threepenny-gui
      - containers
      - stm
  data-memocombinators:
    source-dirs: src/08-data-memocombinators
    main: Main.hs
    dependencies:
      - data-memocombinators
      - time
  sbv:
    source-dirs: src/09-sbv
    main: Main.hs
    dependencies:
      - sbv
  async:
    source-dirs: src/13-async
    main: Main.hs
    dependencies:
      - async
