name: doh2013

dependencies:
  - base

executables:
  linear:
    source-dirs: src/02-linear
    main: Main.hs
    dependencies:
      - linear
      - containers
      - lens
  tasty:
    source-dirs: src/03-tasty
    main: Main.hs
    dependencies:
      - tasty
      - tasty-smallcheck
      - tasty-hunit
